public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1.");
        int i = 7;
        byte b = 120;
        short s = -1000;
        long l = 19797457;
        float f = 64.46f;
        double d = 365.86;
        System.out.println("Значение переменной 'i' с типом 'int' равно: " + i);
        System.out.println("Значение переменной 'b' с типом 'byte' равно: " + b);
        System.out.println("Значение переменной 's' с типом 'short' равно: " + s);
        System.out.println("Значение переменной 'l' с типом 'long' равно: " + l);
        System.out.println("Значение переменной 'f' с типом 'float' равно: " + f);
        System.out.println("Значение переменной 'd' с типом 'double' равно: " + d);
        System.out.println(" ");
        System.out.println("Задача 2.");
        int i2 = 27897;
        byte by2 = 67;
        short s2 = -159;
        long l2 = 987_678_965_549L;
        float f2 = 27.12F;
        double d2 = 2.786;
        boolean b2 = false;
        char c = 569;
        System.out.println(" ");
        System.out.println("Задача 3.");
        int FirstGradeTeacher = 23;
        int SecondGradeTeacher = 27;
        int ThirdGradeTeacher = 30;
        int NumberSheetsPaper= 480;
        int NumberSheetsChildren = NumberSheetsPaper / (FirstGradeTeacher + SecondGradeTeacher + ThirdGradeTeacher);
        System.out.println("На каждого ученика рассчитано " + NumberSheetsChildren + " листов бумаги.");
        System.out.println(" ");
        System.out.println("Задача 4.");
        int Bottles = 16;
        int Minutes = 2;
        int TwentyMinutes = 20;
        int Performance = Bottles / Minutes;
        System.out.println("За " + TwentyMinutes + " минут машина произвела бутылок " + Performance * TwentyMinutes + " штук.");
        int MinInDay = 24 * 60;
        System.out.println("За " + MinInDay + " минут машина произвела бутылок " + Performance * MinInDay + " штук.");
        int MinInThreeDay = MinInDay * 3;
        System.out.println("За " + MinInThreeDay + " минут машина произвела бутылок " + Performance * MinInThreeDay + " штук.");
        int MinInMonth = 10 * MinInThreeDay;
        System.out.println("За " + MinInMonth + " минут машина произвела бутылок " + Performance * MinInMonth + " штук.");
        System.out.println(" ");
        System.out.println("Задача 5.");
        int WholeCansPaints = 120;
        int WhiteCansPaints = 2;
        int BrownCansPaints = 4;
        int NumberClasses = WholeCansPaints / (WhiteCansPaints + BrownCansPaints);
        int WhiteCansPaintsAll = NumberClasses * WhiteCansPaints;
        int BrownCansPaintsAll = NumberClasses * BrownCansPaints;
        System.out.println("В школе, где " + NumberClasses + " классов, нужно " + WhiteCansPaintsAll + " банок белой краски и " + BrownCansPaintsAll + " банок коричневой краски.");
        System.out.println(" ");
        System.out.println("Задача 6.");
        int WeightOneBananas = 80;
        int QuantityBananas = 5;
        int GramProductBananas = QuantityBananas * WeightOneBananas;
        int WeightOneMilk = 105;
        int QuantityMilk = 200;
        int GramProductMilk = WeightOneMilk * (QuantityMilk / 100);
        int WeightOneIceCream = 100;
        int QuantityIceCream = 2;
        int GramProductIceCream = QuantityIceCream * WeightOneIceCream;
        int WeightOneEggs = 70;
        int QuantityEggs = 4;
        int GramProductEggs = QuantityEggs * WeightOneEggs;
        int FinalWeightProduct = GramProductBananas + GramProductMilk + GramProductIceCream + GramProductEggs;
        int grPerKg = 1000;
        float weightKg = FinalWeightProduct/(float)grPerKg;
        System.out.println("Общий вес спорт-завтрака - " + weightKg + " кг.");
        System.out.println(" ");
        System.out.println("Задача 7.");
        int NeedResetKg = 7;
        int NeedResetGram = 7 * 1000;
        int WeightLoss1 = 250;
        int WeightLoss2 = 500;
        int QuantityFirstCase = NeedResetGram / WeightLoss1;
        System.out.println( QuantityFirstCase + " дней уйдёт на похудение, если спортсмен будет терять каждый день по 250 грамм.");
        int QuantitySecondCase = NeedResetGram / WeightLoss2;
        System.out.println( QuantitySecondCase + " дней уйдёт на похудение, если спортсмен будет терять каждый день по 500 грамм.");
        int AverageAmountGram = (WeightLoss1 + WeightLoss2) / 2;
        int AverageDays = NeedResetGram / AverageAmountGram;
        System.out.println(AverageDays + " дней уйдёт в среднем, чтобы добиться результата похудения.");
        System.out.println(" ");
        System.out.println("Задача 8.");
        int MashaMonth = 67760;
        double MashaMonthNew = MashaMonth + (MashaMonth * 0.1);
        double MashaGrowthYear = (MashaMonthNew - MashaMonth) * 12;
        System.out.println ("Маша теперь получает " + MashaMonthNew + " рублей. Годовой доход вырос на " + MashaGrowthYear + " рублей.");
        int DenisMonth = 83690;
        double DenisMonthNew = DenisMonth + (DenisMonth * 0.1);
        double DenisGrowthYear = (DenisMonthNew - DenisMonth) * 12;
        System.out.println ("Денис теперь получает " + DenisMonthNew + " рублей. Годовой доход вырос на " + DenisGrowthYear + " рублей.");
        int KristinaMonth = 76230;
        double KristinaMonthNew = KristinaMonth + (KristinaMonth * 0.1);
        double KristinaGrowthYear = (KristinaMonthNew - KristinaMonth) * 12;
        System.out.println ("Кристина теперь получает " + KristinaMonthNew + " рублей. Годовой доход вырос на " + KristinaGrowthYear + " рублей.");
    }
}